server:
  port: 8100
spring:
  application:
    name: eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka
    register-with-eureka: false
    fetch-registry: false
#关闭自我保护机制
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 50000
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30



